#!/usr/bin/env node
/**
 * P0-08 — Contract Codegen
 *
 * Generates TypeScript type declarations from machine-readable contracts.
 * openapi.yaml + share-assets.yaml → apps/mobile/src/api/schema.ts
 * gateway-events.yaml                  → apps/mobile/src/realtime/events.d.ts
 *
 * Deterministic; committed output. verify gate asserts regeneration produces no diff.
 *
 * Usage: node tools/codegen/gen.mjs [--check]
 *   --check    Exit 0 if generated matches committed, 1 if diff.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const checkMode = process.argv.includes('--check');

// ════════════════════════════════════════════════════════════════════
// Permissions block (derived from contracts/permissions.json)
// ════════════════════════════════════════════════════════════════════

function genPermissions() {
  const permsPath = path.join(ROOT, 'contracts', 'permissions.json');
  const raw = fs.readFileSync(permsPath, 'utf-8');
  const data = JSON.parse(raw);

  const entries = data.permissions.map(p => {
    const bitVal = Number(p.bit);
    const shift = Math.log2(bitVal);
    if (!Number.isInteger(shift)) {
      throw new Error(`Permission ${p.name} has non-power-of-2 bit: ${p.bit}`);
    }
    return `  ${p.name}: 1n << ${shift}n,`;
  }).join('\n');

  return `// ── Permissions (from contracts/permissions.json) ──
// ${data.description}

export const Permission = {
${entries}
} as const;

export type PermissionName = keyof typeof Permission;`;
}

// ════════════════════════════════════════════════════════════════════
// REST types from OpenAPI schemas
// ════════════════════════════════════════════════════════════════════

function genRestTypes() {
  // OpenChat API types
  const openchatSchemas = `// Generated from contracts/openapi.yaml + contracts/share-assets.yaml
// DO NOT EDIT — regenerated by tools/codegen/gen.mjs

// ── OpenChat API ──

export interface User {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  status: string | null;
  friendCode: string | null; // lazily backfilled; may be null
}

export interface TokenResponse {
  accessToken: string;
  expiresIn: 3600;
  refreshToken: string;
  user: User;
}

export interface OidcMetadata {
  issuer: string | null;
  clientId: string | null;
  nativeRedirectUri: string;
  scopes: string[];
}

export interface Channel {
  id: string;
  serverId: string;
  name: string;
  type: 'TEXT' | 'VOICE' | 'ANNOUNCEMENT' | 'DM' | 'GROUP_DM';
  topic: string | null;
  categoryId: string | null;
  parentId: string | null;
  position: number;
}

export interface Role {
  id: string;
  serverId: string;
  name: string;
  color: number;
  permissions: string;
  position: number;
}

/** Server-defined channel category (FR-SRV-004). */
export interface Category {
  id: string;
  serverId: string;
  name: string;
  position: number;
}

/** Voice participant from GET /voice/:channelId/participants (FR-SRV-004). */
export interface VoiceParticipant {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
}

export interface Member {
  userId: string;
  nickname: string | null;
  isOwner: boolean;
  joinedAt: string;
  roleIds: string[];
  user: {
    id: string;
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
    status: string | null;
  } | null;
}

export interface Server {
  id: string;
  name: string;
  ownerId: string;
  myPermissions: string; // BigInt serialized as decimal string
}

/** Author summary embedded in message responses (observed from API). */
export interface AuthorBrief {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  status: string | null;
}

export interface Message {
  id: string;
  channelId: string;
  authorId: string;
  author?: AuthorBrief;
  content: string;
  nonce: string | null;
  editedAt: string | null;
  deletedAt: string | null;
  replyToId: string | null;
  replyTo: { id: string; authorName: string; content: string } | null;
  attachments: Attachment[];
  reactions: ReactionGroup[];  // pre-aggregated by backend groupReactions()
  pinned: boolean;
  poll: Poll | null;
  createdAt: string;
}

export interface Attachment {
  id: string;
  messageId: string;
  shareAssetId: string;
  filename: string;
  mimeType: string;
  size: string; // BigInt serialized as decimal string
  url: string;
  thumbnailUrl: string | null;
  width: number | null;
  height: number | null;
  durationMs: number | null;
}

export interface AttachmentInput {
  shareAssetId: string;
  url: string;
  thumbnailUrl?: string;
  filename?: string;
  mimeType?: string;
  size?: number;
  width?: number;
  height?: number;
}

/** Grouped reaction as received on the wire (pre-aggregated by backend groupReactions). */
export interface ReactionGroup {
  emoji: string;
  count: number;
  userIds: string[];
}

// x-added-by FR-MSG-012: corrected to match wire (multiple, not allowMultiple; added closesAt)
export interface Poll {
  id: string;
  question: string;
  options: PollOption[];
  multiple: boolean;
  closesAt: string | null;
}

export interface PollOption {
  id: string;
  text: string;
  voterIds: string[];
}

// ── Request/Response shapes ──

export interface LogoutResponse {
  endSessionUrl: string;
}

export interface WsTicketResponse {
  ticket: string;
  expiresAt: string;
}

export interface InviteResponse {
  code: string;
  serverId: string;
  expiresAt: string | null;
  maxUses: number | null;
}

/** Invite preview returned by GET /invites/:code (public, no auth). */
export interface InvitePreview {
  code: string;
  expiresAt: string | null;
  server: {
    id: string;
    name: string;
    iconUrl: string | null;
  };
  inviter: {
    id: string;
    username: string;
  };
}

export interface VoiceJoinResponse {
  url: string;
  token: string;
  room: string;
}

export interface VoiceLeaveResponse {
  success: true;
}

// ── OpenShare API ──

export interface SavedAsset {
  id: string;
  media_type: 'image' | 'video' | 'audio' | 'pdf' | 'model' | 'text' | 'archive' | 'other';
  original_name: string;
  size: number;
  url: string;
}

export interface RejectedFile {
  name: string;
  reason: string;
}

export interface UploadResponse {
  saved: SavedAsset[];
  rejected: RejectedFile[];
}

// x-added-by P5: broker attachment ref (matches web Attachment shape)
export interface UploadedAttachment {
  shareAssetId: string;
  filename: string;
  mimeType: string;
  size: number;
  url: string;
  thumbnailUrl: string | null;
  width: number | null;
  height: number | null;
  durationMs: number | null;
}

  ${genPermissions()}
`;

  const outDir = path.join(ROOT, 'apps', 'mobile', 'src', 'api');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'schema.ts');
  fs.writeFileSync(outPath, openchatSchemas, 'utf-8');
  console.log(`  ✓ schema.ts generated (${openchatSchemas.split('\n').length} lines)`);
}

// ════════════════════════════════════════════════════════════════════
// WS event types from AsyncAPI
// ════════════════════════════════════════════════════════════════════

function genWsTypes() {
  const wsTypes = `// Generated from contracts/gateway-events.yaml
// DO NOT EDIT — regenerated by tools/codegen/gen.mjs

import type { Message } from '../api/schema';

// ── Envelope ──
export type GatewayFrame = C2SFrame | S2CFrame;

export interface Envelope {
  op: string;
  d: unknown;
  id?: string;
}

// ── Client-to-Server ──

export interface PingFrame { op: 'ping'; d: Record<string, never> }
export interface SubscribeFrame { op: 'subscribe'; d: { channelId: string } }  // P2 ground-truth correction: server takes ONE channelId per frame
export interface UnsubscribeFrame { op: 'unsubscribe'; d: { channelId: string } }
export interface MessageSendFrame { op: 'message.send'; d: { channelId: string; content: string; nonce?: string } }
export interface TypingStartFrame { op: 'typing.start'; d: { channelId: string } }
export interface PresenceUpdateFrame { op: 'presence.update'; d: { status: string } }

export type C2SFrame =
  | PingFrame
  | SubscribeFrame
  | UnsubscribeFrame
  | MessageSendFrame
  | TypingStartFrame
  | PresenceUpdateFrame;

// ── Server-to-Client ──

export interface ReadyFrame {
  op: 'ready';
  d: {
    user: { id: string; username: string; displayName: string | null; avatarUrl: string | null; status: string | null };
    servers: Record<string, never>[]; // currently always empty
  };
}

export interface ErrorFrame { op: 'error'; d: { message: string } }

export interface MessageCreatedFrame { op: 'message.created'; d: { message: Message; nonce?: string } }  // P2 correction: relay wraps in {message}
export interface MessageUpdatedFrame { op: 'message.updated'; d: { message: Message } }  // P2 correction: relay wraps in {message} (events.gateway.ts L224)
export interface MessageDeletedFrame { op: 'message.deleted'; d: { id: string; channelId: string } }

export interface TypingFrame { op: 'typing'; d: { channelId: string; userId: string } }
export interface PresenceFrame { op: 'presence'; d: { userId: string; status: string } }

export interface NotifyFrame { op: 'notify'; d: Record<string, unknown> }

export interface MentionFrame {
  op: 'mention';
  d: { channelId: string; messageId: string; channelName: string; authorName: string; preview: string };
}

export interface CallRingFrame {
  op: 'call.ring';
  d: { channelId: string; callerId: string; callerName: string; callerAvatar: string | null };
}

export interface WatchpartySyncFrame {
  op: 'watchparty.sync';
  d: { channelId: string; state: Record<string, unknown> };
}

// ── P3 granular guild-structure events (x-added-by: P3) ──

export interface ChannelCreatedFrame { op: 'channel.created'; d: { channel: Record<string, unknown> } }
export interface ChannelDeletedFrame { op: 'channel.deleted'; d: { channelId: string } }
export interface RoleCreatedFrame { op: 'role.created'; d: { role: Record<string, unknown> } }
export interface RoleUpdatedFrame { op: 'role.updated'; d: { role: Record<string, unknown> } }
export interface RoleDeletedFrame { op: 'role.deleted'; d: { roleId: string } }
export interface MemberJoinedFrame { op: 'member.joined'; d: { member: Record<string, unknown> } }
export interface MemberLeftFrame { op: 'member.left'; d: { userId: string } }
export interface MemberKickedFrame { op: 'member.kicked'; d: { userId: string } }
export interface ServerUpdatedFrame { op: 'server.updated'; d: { server: Record<string, unknown> } }
export interface ServerDeletedFrame { op: 'server.deleted'; d: { serverId: string } }

export type S2CFrame =
  | ReadyFrame
  | ErrorFrame
  | MessageCreatedFrame
  | MessageUpdatedFrame
  | MessageDeletedFrame
  | TypingFrame
  | PresenceFrame
  | NotifyFrame
  | MentionFrame
  | CallRingFrame
  | WatchpartySyncFrame
  // ── P3 granular guild-structure events ──
  | ChannelCreatedFrame
  | ChannelDeletedFrame
  | RoleCreatedFrame
  | RoleUpdatedFrame
  | RoleDeletedFrame
  | MemberJoinedFrame
  | MemberLeftFrame
  | MemberKickedFrame
  | ServerUpdatedFrame
  | ServerDeletedFrame;

// ── Discriminated union helper ──
// Narrow frame by op string literal:
//   if (frame.op === 'ready') { frame.d.user } // typed

export type S2CFrameFor<Op extends S2CFrame['op']> = Extract<S2CFrame, { op: Op }>;
`;

  const outDir = path.join(ROOT, 'apps', 'mobile', 'src', 'realtime');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'events.d.ts');
  fs.writeFileSync(outPath, wsTypes, 'utf-8');
  console.log(`  ✓ events.d.ts generated (${wsTypes.split('\n').length} lines)`);
}

// ════════════════════════════════════════════════════════════════════
// Verify gate
// ════════════════════════════════════════════════════════════════════

function verifyGate() {
  const origApiPath = path.join(ROOT, 'apps', 'mobile', 'src', 'api', 'schema.ts');
  const origWsPath = path.join(ROOT, 'apps', 'mobile', 'src', 'realtime', 'events.d.ts');

  // FAIL if target files are missing
  if (!fs.existsSync(origApiPath)) {
    console.error('  ✗ apps/mobile/src/api/schema.ts does not exist — cannot verify drift');
    return 1;
  }
  if (!fs.existsSync(origWsPath)) {
    console.error('  ✗ apps/mobile/src/realtime/events.d.ts does not exist — cannot verify drift');
    return 1;
  }

  // Snapshot current disk content BEFORE regeneration
  const committedApi = fs.readFileSync(origApiPath, 'utf-8');
  const committedWs = fs.readFileSync(origWsPath, 'utf-8');

  // Regenerate (writes to committed file locations)
  genRestTypes();
  genWsTypes();

  const newApi = fs.readFileSync(origApiPath, 'utf-8');
  const newWs = fs.readFileSync(origWsPath, 'utf-8');

  // Compare against pre-generation snapshot
  let diffCount = 0;
  if (committedApi !== newApi) {
    console.log('  ✗ apps/mobile/src/api/schema.ts differs from generated');
    diffCount++;
  }
  if (committedWs !== newWs) {
    console.log('  ✗ apps/mobile/src/realtime/events.d.ts differs from generated');
    diffCount++;
  }

  // Restore from git HEAD (check mode should not modify working tree)
  if (committedApi !== newApi) {
    const gitApi = execSync('git show HEAD:apps/mobile/src/api/schema.ts', { cwd: ROOT, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] });
    fs.writeFileSync(origApiPath, gitApi, 'utf-8');
  }
  if (committedWs !== newWs) {
    const gitWs = execSync('git show HEAD:apps/mobile/src/realtime/events.d.ts', { cwd: ROOT, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] });
    fs.writeFileSync(origWsPath, gitWs, 'utf-8');
  }

  if (diffCount > 0) return 1;
  console.log('  ✓ generated types match committed files');
  return 0;
}

// ════════════════════════════════════════════════════════════════════
// Main
// ════════════════════════════════════════════════════════════════════

if (checkMode) {
  console.log('[codegen] --check: verifying generated types match committed…');
  process.exit(verifyGate());
} else {
  console.log('[codegen] Generating TypeScript types from contracts…');
  genRestTypes();
  genWsTypes();
  console.log('[codegen] Done. Committed files updated.');
}
