// Generated from contracts/openapi.yaml + contracts/share-assets.yaml
// DO NOT EDIT — regenerated by tools/codegen/gen.mjs

// ── OpenChat API ──

export interface User {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  status: string | null;
  friendCode: string | null; // lazily backfilled; may be null
}

export interface TokenResponse {
  accessToken: string;
  expiresIn: 3600;
  refreshToken: string;
  user: User;
}

export interface OidcMetadata {
  issuer: string | null;
  clientId: string | null;
  nativeRedirectUri: string;
  scopes: string[];
}

export interface Channel {
  id: string;
  serverId: string;
  name: string;
  type: 'TEXT' | 'VOICE' | 'ANNOUNCEMENT' | 'DM' | 'GROUP_DM';
  topic: string | null;
  categoryId: string | null;
  parentId: string | null;
  position: number;
}

export interface Member {
  userId: string;
  nickname: string | null;
  isOwner: boolean;
  joinedAt: string;
  roleIds: string[];
  user: {
    id: string;
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
    status: string | null;
  } | null;
}

export interface Server {
  id: string;
  name: string;
  ownerId: string;
  myPermissions: string; // BigInt serialized as decimal string
}

/** Author summary embedded in message responses (observed from API). */
export interface AuthorBrief {
  id: string;
  username: string;
  displayName: string | null;
  avatarUrl: string | null;
  status: string | null;
}

export interface Message {
  id: string;
  channelId: string;
  authorId: string;
  author?: AuthorBrief;
  content: string;
  nonce: string | null;
  editedAt: string | null;
  deletedAt: string | null;
  replyToId: string | null;
  replyTo: { id: string; authorName: string; content: string } | null;
  attachments: Attachment[];
  reactions: ReactionGroup[];  // pre-aggregated by backend groupReactions()
  pinned: boolean;
  poll: Poll | null;
  createdAt: string;
}

export interface Attachment {
  id: string;
  messageId: string;
  shareAssetId: string;
  filename: string;
  mimeType: string;
  size: string; // BigInt serialized as decimal string
  url: string;
  thumbnailUrl: string | null;
  width: number | null;
  height: number | null;
  durationMs: number | null;
}

export interface AttachmentInput {
  shareAssetId: string;
  url: string;
  thumbnailUrl?: string;
  filename?: string;
  mimeType?: string;
  size?: number;
  width?: number;
  height?: number;
}

/** Grouped reaction as received on the wire (pre-aggregated by backend groupReactions). */
export interface ReactionGroup {
  emoji: string;
  count: number;
  userIds: string[];
}

// x-added-by FR-MSG-012: corrected to match wire (multiple, not allowMultiple; added closesAt)
export interface Poll {
  id: string;
  question: string;
  options: PollOption[];
  multiple: boolean;
  closesAt: string | null;
}

export interface PollOption {
  id: string;
  text: string;
  voterIds: string[];
}

// ── Request/Response shapes ──

export interface LogoutResponse {
  endSessionUrl: string;
}

export interface WsTicketResponse {
  ticket: string;
  expiresAt: string;
}

export interface InviteResponse {
  code: string;
  serverId: string;
  expiresAt: string | null;
  maxUses: number | null;
}

/** FR-SRV-006 — Invite preview (GET /invites/:code). */
export interface InvitePreview {
  code: string;
  expiresAt: string | null;
  server: {
    id: string;
    name: string;
    iconUrl: string | null;
  };
  inviter: {
    id: string;
    username: string;
  };
}

export interface VoiceJoinResponse {
  url: string;
  token: string;
  room: string;
}

export interface VoiceLeaveResponse {
  success: true;
}

// ── OpenShare API ──

export interface SavedAsset {
  id: string;
  media_type: 'image' | 'video' | 'audio' | 'pdf' | 'model' | 'text' | 'archive' | 'other';
  original_name: string;
  size: number;
  url: string;
}

export interface RejectedFile {
  name: string;
  reason: string;
}

export interface UploadResponse {
  saved: SavedAsset[];
  rejected: RejectedFile[];
}

  // ── Permissions (from contracts/permissions.json) ──
// Server permission bitfield names and values. Source: apps/api/src/permissions/permissions.ts. This file is derived from the single source of truth in TypeScript; codegen copies it.

export const Permission = {
  ADMINISTRATOR: 1n << 0n,
  MANAGE_SERVER: 1n << 1n,
  MANAGE_CHANNELS: 1n << 2n,
  MANAGE_ROLES: 1n << 3n,
  MANAGE_MEMBERS: 1n << 4n,
  CREATE_INVITE: 1n << 5n,
  MANAGE_MESSAGES: 1n << 6n,
  MENTION_EVERYONE: 1n << 7n,
  BAN_MEMBERS: 1n << 8n,
  SEND_MESSAGES: 1n << 9n,
  READ_MESSAGES: 1n << 10n,
} as const;

export type PermissionName = keyof typeof Permission;
