// Generated from contracts/gateway-events.yaml
// DO NOT EDIT — regenerated by tools/codegen/gen.mjs

import type { Message } from '../api/schema';

// ── Envelope ──
export type GatewayFrame = C2SFrame | S2CFrame;

export interface Envelope {
  op: string;
  d: unknown;
  id?: string;
}

// ── Client-to-Server ──

export interface PingFrame { op: 'ping'; d: Record<string, never> }
export interface SubscribeFrame { op: 'subscribe'; d: { channelId: string } }  // P2 ground-truth correction: server takes ONE channelId per frame
export interface UnsubscribeFrame { op: 'unsubscribe'; d: { channelId: string } }
export interface MessageSendFrame { op: 'message.send'; d: { channelId: string; content: string; nonce?: string } }
export interface TypingStartFrame { op: 'typing.start'; d: { channelId: string } }
export interface PresenceUpdateFrame { op: 'presence.update'; d: { status: string } }

export type C2SFrame =
  | PingFrame
  | SubscribeFrame
  | UnsubscribeFrame
  | MessageSendFrame
  | TypingStartFrame
  | PresenceUpdateFrame;

// ── Server-to-Client ──

export interface ReadyFrame {
  op: 'ready';
  d: {
    user: { id: string; username: string; displayName: string | null; avatarUrl: string | null; status: string | null };
    servers: Record<string, never>[]; // currently always empty
  };
}

export interface ErrorFrame { op: 'error'; d: { message: string } }

export interface MessageCreatedFrame { op: 'message.created'; d: { message: Message; nonce?: string } }  // P2 correction: relay wraps in {message}
export interface MessageUpdatedFrame { op: 'message.updated'; d: { message: Message } }  // P2 correction: relay wraps in {message} (events.gateway.ts L224)
export interface MessageDeletedFrame { op: 'message.deleted'; d: { id: string; channelId: string } }

export interface TypingFrame { op: 'typing'; d: { channelId: string; userId: string } }
export interface PresenceFrame { op: 'presence'; d: { userId: string; status: string } }

export interface NotifyFrame { op: 'notify'; d: Record<string, unknown> }

export interface MentionFrame {
  op: 'mention';
  d: { channelId: string; messageId: string; channelName: string; authorName: string; preview: string };
}

export interface CallRingFrame {
  op: 'call.ring';
  d: { channelId: string; callerId: string; callerName: string; callerAvatar: string | null };
}

export interface WatchpartySyncFrame {
  op: 'watchparty.sync';
  d: { channelId: string; state: Record<string, unknown> };
}

export interface VoiceOccupancyFrame {
  op: 'voice.occupancy';
  d: { channelId: string };
}

// ── P3 granular guild-structure events (x-added-by: P3) ──

export interface ChannelCreatedFrame { op: 'channel.created'; d: { channel: Record<string, unknown> } }
export interface ChannelDeletedFrame { op: 'channel.deleted'; d: { channelId: string } }
export interface RoleCreatedFrame { op: 'role.created'; d: { role: Record<string, unknown> } }
export interface RoleUpdatedFrame { op: 'role.updated'; d: { role: Record<string, unknown> } }
export interface RoleDeletedFrame { op: 'role.deleted'; d: { roleId: string } }
export interface MemberJoinedFrame { op: 'member.joined'; d: { member: Record<string, unknown> } }
export interface MemberLeftFrame { op: 'member.left'; d: { userId: string } }
export interface MemberKickedFrame { op: 'member.kicked'; d: { userId: string } }
export interface ServerUpdatedFrame { op: 'server.updated'; d: { server: Record<string, unknown> } }
export interface ServerDeletedFrame { op: 'server.deleted'; d: { serverId: string } }

export type S2CFrame =
  | ReadyFrame
  | ErrorFrame
  | MessageCreatedFrame
  | MessageUpdatedFrame
  | MessageDeletedFrame
  | TypingFrame
  | PresenceFrame
  | NotifyFrame
  | MentionFrame
  | CallRingFrame
  | WatchpartySyncFrame
  // ── P3 granular guild-structure events ──
  | VoiceOccupancyFrame
  | ChannelCreatedFrame
  | ChannelDeletedFrame
  | RoleCreatedFrame
  | RoleUpdatedFrame
  | RoleDeletedFrame
  | MemberJoinedFrame
  | MemberLeftFrame
  | MemberKickedFrame
  | ServerUpdatedFrame
  | ServerDeletedFrame;

// ── Discriminated union helper ──
// Narrow frame by op string literal:
//   if (frame.op === 'ready') { frame.d.user } // typed

export type S2CFrameFor<Op extends S2CFrame['op']> = Extract<S2CFrame, { op: Op }>;
