/**
 * Strings — every user-facing string in the app (NFR-11).
 *
 * Content is English-only for v1, but nothing renders a literal: a lint rule
 * rejects literal JSX text, so adding a locale later is a data change rather
 * than a hunt through the component tree.
 */

export const strings = {
  app: {
    name: 'OpenChat',
  },
  hello: {
    title: 'OpenChat',
    subtitle: 'Skeleton build — no features yet (P0-17)',
  },
  auth: {
    title: 'OpenChat',
    subtitle: 'Sign in to get started',
    usernamePlaceholder: 'Username',
    devLoginButton: 'Sign in (dev)',
    loginFailed: 'Sign-in failed',
    loggingIn: 'Signing in…',
  },
  shell: {
    hamburger: '\u2630',
    channelHash: '#',
    hamburgerIcon: '☰',
    channelsFallbackTitle: 'Channels',
    noServers: 'No servers yet',
    noChannels: 'No channels',
    selectChannel: 'Select a channel',
    chatPlaceholder: 'Messages arrive in Phase 2',
    membersTitle: 'Members',
    menuGlyph: '\u2630',
    settingsGear: '\u2699',
    logout: 'Sign out',
  },
  messages: {
    empty: 'No messages yet',
    composerPlaceholder: 'Message',
    send: 'Send',
    sendFailed: 'Message failed to send',
    edited: '(edited)',
    deleted: 'Message removed',
    react: 'React',
    edit: 'Edit',
    delete: 'Delete',
    copyText: 'Copy text',
    copyLink: 'Copy link',
    editTitle: 'Edit message',
    editSave: 'Save',
    editCancel: 'Cancel',
    deleteConfirm: 'Delete this message?',
    deleteConfirmOk: 'Delete',
    editFailed: 'Edit failed',
    deleteFailed: 'Delete failed',
    pin: 'Pin',
    unpin: 'Unpin',
    pinFailed: 'Pin failed',
    pinsPanelTitle: 'Pinned messages',
    pinsEmpty: 'No pinned messages',
    pinIcon: '📌',
    closeIcon: '✕',
    announcementReadOnly: 'You do not have permission to send in this announcement channel',
    reply: 'Reply',
    replyingTo: 'Replying to',
    replyCancel: 'Cancel reply',
    replyNotFound: 'Original message not found',
  },
  mentions: {
    everyoneLabel: '@everyone',
    hereLabel: '@here',
  },
  reactions: {
    pickerTitle: 'Add reaction',
    pickerSearchPlaceholder: 'Search emoji',
    reactorListTitle: 'Reactions',
    noReactors: '—',
  },
  connection: {
    offline: 'Offline — reconnecting…',
    connecting: 'Connecting…',
  },
  profile: {
    title: 'Account',
    displayNameLabel: 'Display name',
    save: 'Save',
    saved: 'Profile updated',
    saveFailed: 'Could not update profile',
  },
  typing: {
    one: 'is typing\u2026',
    two: 'are typing\u2026',
    twoConjunction: 'and',
    many: 'Several people are typing\u2026',
  },
  embeds: {
    youtubeTitle: 'YouTube',
    linkTitle: 'Link',
    openLink: 'Open link',
    youtubePlay: '▶',
    shareSeparator: '/',
    linkIcon: '🔗',
  },
  gifs: {
    searchPlaceholder: 'Search GIFs…',
    loading: 'Loading…',
    searchFailed: 'GIF search failed',
    notConfigured: 'GIF search is not configured',
    poweredBy: 'Powered by GIPHY',
    button: 'GIF',
    close: '✕',
  },
  poll: {
    createTitle: 'Create Poll',
    chartIcon: '📊',
    closeIcon: '\u2715',
    percentSign: '%',
    totalLabel: 'total',
    questionPlaceholder: 'Ask a question…',
    optionPlaceholder: 'Option',
    addOption: '+ Add option',
    removeOption: 'Remove',
    create: 'Create',
    createFailed: 'Failed to create poll',
    optionsTooFew: 'Add at least 2 options',
    optionsTooMany: 'Maximum 10 options allowed',
    voteFailed: 'Vote failed',
    closed: 'Poll closed',
    totalVotes: 'vote',
    totalVotesPlural: 'votes',
    multipleLabel: 'Allow multiple choices',
  },
  servers: {
    createTitle: 'Create Server',
    createNamePlaceholder: 'Server name',
    createButton: 'Create',
    createFailed: 'Failed to create server',
    settingsTitle: 'Server Settings',
    renameLabel: 'Server name',
    renameSave: 'Save',
    renameSaved: 'Server renamed',
    renameFailed: 'Failed to rename server',
    deleteTitle: 'Delete Server',
    deleteConfirm: 'Are you sure you want to delete this server? This action cannot be undone.',
    deleteButton: 'Delete Server',
    deleteConfirmButton: 'Delete',
    deleteFailed: 'Failed to delete server',
    settingsButton: 'Settings',
    createButtonNav: '+',
    renameDenied: 'You need the Manage Server permission to rename this server.',
    deleteDenied: 'Only the server owner can delete this server.',
  },
  invites: {
    joinTitle: 'Join a server',
    codePlaceholder: 'Enter invite code',
    join: 'Join',
    joinFailed: 'Failed to join server',
    previewTitle: "You've been invited!",
    previewServer: 'Server',
    previewInviter: 'Invited by',
    accept: 'Accept',
    decline: 'Decline',
    acceptFailed: 'Failed to accept invite',
    invalidCode: 'Invalid invite code',
    createTitle: 'Invite',
    createInvite: 'Create invite link',
    creating: 'Creating…',
    createFailed: 'Failed to create invite',
    shareTitle: 'Share invite link',
    copy: 'Copy',
    copied: 'Copied!',
    noPermission: 'You cannot create invites in this server',
    expiresLabel: 'Expires:',
  },
  channels: {
    categoryDefault: 'Uncategorized',
    voicePrefix: '\u{1F50A}',
    voiceParticipants: '{count} connected',
    createTitle: 'Create Channel',
    editTitle: 'Edit Channel',
    nameLabel: 'Channel name',
    typeLabel: 'Channel type',
    categoryLabel: 'Category',
    topicLabel: 'Topic',
    save: 'Create',
    saveEdit: 'Save',
    deleteConfirm: 'Delete this channel?',
    deleteConfirmOk: 'Delete',
    reorderTitle: 'Reorder Channels',
    reorderHint: 'Drag to reorder — up/down arrows',
    noCategory: 'No category',
    noVoiceParticipants: '0 connected',
    typeText: '# TEXT',
    typeVoice: '\u{1F50A} VOICE',
    createAction: '+',
    reorderAction: '\u2630',
    editAction: '\u270E',
    deleteAction: '\u2715',
    moveUpAction: '\u25B2',
    moveDownAction: '\u25BC',
    typeAnnouncement: '📢 ANNOUNCEMENT',
  },
  roles: {
    title: 'Roles',
    create: 'Create Role',
    noRoles: 'No roles',
    editTitle: 'Edit Role',
    createTitle: 'Create Role',
    namePlaceholder: 'Role name',
    colorLabel: 'Color',
    save: 'Save',
    delete: 'Delete',
    confirmDelete: 'Delete this role?',
    permissionsLabel: 'Permissions',
  },
  common: {
    retry: 'Retry',
    cancel: 'Cancel',
    error: 'Something went wrong',
  },
  attachments: {
    imageGrid: 'Image attachments',
    imageLabel: 'Image',
    closeGallery: 'Close gallery',
    closeIcon: '\u2715',
    share: 'Share',
    shareIcon: '\u2B06',
    galleryCounterSeparator: '\u00A0/\u00A0',
  },
  members: {
    title: 'Members',
    empty: 'No members',
    crown: '\u2655',
    ownerBadge: 'Server Owner',
    nickname: 'Nickname',
    nicknameColon: 'Nickname:',
    usernamePrefix: '@',
    kick: 'Kick',
    leave: 'Leave Server',
    kickConfirm: 'Kick this member?',
    kickConfirmOk: 'Kick',
    leaveConfirm: 'Leave this server?',
    leaveConfirmOk: 'Leave',
  },
  presence: {
    title: 'Set Status',
    statusLabel: 'Presence status',
    updateFailed: 'Could not update status',
    chevronDown: '\u25BC',
    checkmark: '\u2713',
  },
  avatars: {
    placeholder: '?',
    pickButton: 'Choose image',
    uploadFailed: 'Upload failed',
    saveFailed: 'Could not save avatar',
    avatarSaved: 'Avatar updated',
    avatarLabel: 'Avatar',
    iconLabel: 'Server icon',
    iconSaved: 'Server icon updated',
  },
  // FR-MED-010 — compose attachments
  attachments: {
    pickerTitle: 'Add attachment',
    photoLibrary: 'Photo Library',
    photoLibraryIcon: '\u{1F4F7}',
    camera: 'Camera',
    cameraIcon: '\u{1F4F8}',
    files: 'Files',
    filesIcon: '\u{1F4C1}',
    cancel: 'Cancel',
    remove: 'Remove',
    closeIcon: '\u2715',
    doneIcon: '\u2713',
    fileIcon: '\u{1F4C4}',
    originalToggle: 'Original',
    cancelUpload: 'Cancel upload',
    attach: '+',
    uploadFailed: 'Upload failed',
    uploading: 'Uploading\u2026',
    tooManyFiles: 'Maximum 10 files per message',
    fileTooLarge: 'File too large (100 MB)',
  },
} as const;

export type Strings = typeof strings;
