/**
 * Strings — every user-facing string in the app (NFR-11).
 *
 * Content is English-only for v1, but nothing renders a literal: a lint rule
 * rejects literal JSX text, so adding a locale later is a data change rather
 * than a hunt through the component tree.
 */

export const strings = {
  app: {
    name: 'OpenChat',
  },
  hello: {
    title: 'OpenChat',
    subtitle: 'Skeleton build — no features yet (P0-17)',
  },
  auth: {
    title: 'OpenChat',
    subtitle: 'Sign in to get started',
    usernamePlaceholder: 'Username',
    devLoginButton: 'Sign in (dev)',
    loginFailed: 'Sign-in failed',
    loggingIn: 'Signing in…',
  },
  shell: {
    hamburger: '\u2630',
    channelHash: '#',
    hamburgerIcon: '☰',
    channelsFallbackTitle: 'Channels',
    noServers: 'No servers yet',
    noChannels: 'No channels',
    selectChannel: 'Select a channel',
    chatPlaceholder: 'Messages arrive in Phase 2',
    membersTitle: 'Members',
    menuGlyph: '\u2630',
    settingsGear: '\u2699',
    logout: 'Sign out',
  },
  messages: {
    empty: 'No messages yet',
    composerPlaceholder: 'Message',
    send: 'Send',
    sendFailed: 'Message failed to send',
    edited: '(edited)',
    deleted: 'Message removed',
    react: 'React',
    edit: 'Edit',
    delete: 'Delete',
    copyText: 'Copy text',
    copyLink: 'Copy link',
    editTitle: 'Edit message',
    editSave: 'Save',
    editCancel: 'Cancel',
    deleteConfirm: 'Delete this message?',
    deleteConfirmOk: 'Delete',
    editFailed: 'Edit failed',
    deleteFailed: 'Delete failed',
    pin: 'Pin',
    unpin: 'Unpin',
    pinFailed: 'Pin failed',
    pinsPanelTitle: 'Pinned messages',
    pinsEmpty: 'No pinned messages',
    pinIcon: '📌',
    closeIcon: '✕',
    reply: 'Reply',
    replyingTo: 'Replying to',
    replyCancel: 'Cancel reply',
    replyNotFound: 'Original message not found',
  },
  mentions: {
    everyoneLabel: '@everyone',
    hereLabel: '@here',
  },
  reactions: {
    pickerTitle: 'Add reaction',
    pickerSearchPlaceholder: 'Search emoji',
    reactorListTitle: 'Reactions',
    noReactors: '—',
  },
  connection: {
    offline: 'Offline — reconnecting…',
    connecting: 'Connecting…',
  },
  profile: {
    title: 'Account',
    displayNameLabel: 'Display name',
    save: 'Save',
    saved: 'Profile updated',
    saveFailed: 'Could not update profile',
  },
  typing: {
    one: 'is typing\u2026',
    two: 'are typing\u2026',
    twoConjunction: 'and',
    many: 'Several people are typing\u2026',
  },
  embeds: {
    youtubeTitle: 'YouTube',
    linkTitle: 'Link',
    openLink: 'Open link',
    youtubePlay: '▶',
    shareSeparator: '/',
    linkIcon: '🔗',
  },
  gifs: {
    searchPlaceholder: 'Search GIFs…',
    loading: 'Loading…',
    searchFailed: 'GIF search failed',
    notConfigured: 'GIF search is not configured',
    poweredBy: 'Powered by GIPHY',
    button: 'GIF',
    close: '✕',
  },
  poll: {
    createTitle: 'Create Poll',
    chartIcon: '📊',
    closeIcon: '\u2715',
    percentSign: '%',
    totalLabel: 'total',
    questionPlaceholder: 'Ask a question…',
    optionPlaceholder: 'Option',
    addOption: '+ Add option',
    removeOption: 'Remove',
    create: 'Create',
    createFailed: 'Failed to create poll',
    optionsTooFew: 'Add at least 2 options',
    optionsTooMany: 'Maximum 10 options allowed',
    voteFailed: 'Vote failed',
    closed: 'Poll closed',
    totalVotes: 'vote',
    totalVotesPlural: 'votes',
    multipleLabel: 'Allow multiple choices',
  },
  servers: {
    createTitle: 'Create Server',
    createNamePlaceholder: 'Server name',
    createButton: 'Create',
    createFailed: 'Failed to create server',
    settingsTitle: 'Server Settings',
    renameLabel: 'Server name',
    renameSave: 'Save',
    renameSaved: 'Server renamed',
    renameFailed: 'Failed to rename server',
    deleteTitle: 'Delete Server',
    deleteConfirm: 'Are you sure you want to delete this server? This action cannot be undone.',
    deleteButton: 'Delete Server',
    deleteConfirmButton: 'Delete',
    deleteFailed: 'Failed to delete server',
    settingsButton: 'Settings',
    createButtonNav: '+',
    renameDenied: 'You need the Manage Server permission to rename this server.',
    deleteDenied: 'Only the server owner can delete this server.',
  },
  invites: {
    joinTitle: 'Join a server',
    codePlaceholder: 'Enter invite code',
    join: 'Join',
    joinFailed: 'Failed to join server',
    previewTitle: "You've been invited!",
    previewServer: 'Server',
    previewInviter: 'Invited by',
    accept: 'Accept',
    decline: 'Decline',
    acceptFailed: 'Failed to accept invite',
    invalidCode: 'Invalid invite code',
    createTitle: 'Invite',
    createInvite: 'Create invite link',
    creating: 'Creating…',
    createFailed: 'Failed to create invite',
    shareTitle: 'Share invite link',
    copy: 'Copy',
    copied: 'Copied!',
    noPermission: 'You cannot create invites in this server',
    expiresLabel: 'Expires:',
  },
  common: {
    retry: 'Retry',
    cancel: 'Cancel',
    error: 'Something went wrong',
  },
} as const;

export type Strings = typeof strings;
