#!/usr/bin/env bash
# =============================================================================
# worktree-up.sh — bootstrap a worktree for bare-metal API testing
#
# Idempotent. Given a worktree path and an API port, leaves that worktree
# ready to run tests. Writes apps/api/.env from canonical dev values,
# installs deps if needed, and prints the start command.
#
# Usage:  tools/worktree-up.sh <worktree-path> <port>
#
# Source of truth: docker-compose.dev.yml (api service env block) + .env.dev.
# DATABASE_URL and REDIS_URL point at the SHARED dev stack on localhost
# (postgres :5432, redis :6379). The worktree API runs natively, not in Docker.
#
# NEVER commits .env. NEVER prints secret values. Confirms .gitignore
# coverage before finishing.
# =============================================================================
set -euo pipefail

WORKTREE="${1:?Usage: worktree-up.sh <worktree-path> <port>}"
PORT="${2:?Usage: worktree-up.sh <worktree-path> <port>}"

if [ ! -d "$WORKTREE" ]; then
  echo "ERROR: worktree path does not exist: $WORKTREE"
  exit 1
fi

API_DIR="$WORKTREE/apps/api"
if [ ! -d "$API_DIR" ]; then
  echo "ERROR: not an OpenChat worktree (no apps/api): $WORKTREE"
  exit 1
fi

# ── .env (idempotent) ─────────────────────────────────────────────────
ENV_FILE="$API_DIR/.env"

cat > "$ENV_FILE" <<EOF
# Generated by tools/worktree-up.sh — DO NOT COMMIT
# Bare-metal API env pointing at the shared dev stack on localhost.

NODE_ENV=development
DEV_AUTH=1
API_PORT=$PORT
WEB_ORIGIN=http://localhost:3000
WEB_PORT=3000

# Postgres — shared dev stack on localhost (postgres:chat from docker-compose.dev.yml)
DATABASE_URL=postgresql://chat:chat@localhost:5432/chat
REDIS_URL=redis://localhost:6379

# OIDC (placeholder — DEV_AUTH=1 bypasses Auth)
OIDC_ISSUER=https://auth.example.com/application/o/chat/
OIDC_CLIENT_ID=dev
OIDC_CLIENT_SECRET=dev-oidc-secret-not-for-prod
OIDC_REDIRECT_URI=http://localhost:3000/api/auth/callback
OIDC_POST_LOGOUT_REDIRECT_URI=http://localhost:3000

# OpenShare
SHARE_BASE_URL=http://localhost:8800
SHARE_API_KEY=dev-share-key

# Jellyfin
JELLYFIN_URL=http://localhost:8096
JELLYFIN_API_KEY=

# LiveKit (dev keys from docker-compose.dev.yml)
LIVEKIT_URL=ws://localhost:7880
LIVEKIT_API_KEY=devkey
LIVEKIT_API_SECRET=secretsecretsecretsecretsecret12
LIVEKIT_API_URL=http://localhost:7880

# Giphy
GIPHY_API_KEY=

# P1-01: bearer access tokens (from docker-compose.dev.yml)
SESSION_SECRET=dev-dev-dev-dev-16
JWT_SECRET=dev-jwt-secret-not-for-prod
EOF

echo "[worktree-up] Wrote $ENV_FILE"

# ── Confirm .env is gitignored ────────────────────────────────────────
pushd "$WORKTREE" > /dev/null
if git check-ignore "$ENV_FILE" > /dev/null 2>&1; then
  echo "[worktree-up] Confirmed .env is gitignored"
else
  echo "ERROR: apps/api/.env is NOT gitignored in this worktree — refusing to proceed"
  popd > /dev/null
  exit 1
fi
popd > /dev/null

# ── Dependencies (idempotent) ─────────────────────────────────────────
if [ ! -d "$API_DIR/node_modules" ]; then
  echo "[worktree-up] Installing dependencies (npm ci)..."
  (cd "$API_DIR" && npm ci --silent)
else
  echo "[worktree-up] node_modules present — skipping npm ci"
fi

# ── Prisma generate (idempotent) ──────────────────────────────────────
echo "[worktree-up] Running prisma generate..."
(cd "$API_DIR" && npx prisma generate --schema=prisma/schema.prisma > /dev/null)

echo ""
echo "✅ Worktree ready. Start the API with:"
echo "   PORT=$PORT npm run start:dev"
echo "   (run this in: $API_DIR)"
