#!/usr/bin/env bash
# =============================================================================
# worktree-up.sh — bootstrap a worktree for bare-metal API testing
#
# Idempotent. Given a worktree path and an API port, leaves that worktree
# ready to run tests. Writes apps/api/.env from canonical dev values,
# installs deps if needed, and prints the start command.
#
# Usage:  tools/worktree-up.sh <worktree-path> <port>
#
# Source of truth: docker-compose.dev.yml (api service env block) + .env.dev.
# DATABASE_URL and REDIS_URL point at the SHARED dev stack on localhost
# (postgres :5432, redis :6379). The worktree API runs natively, not in Docker.
#
# NEVER commits .env. NEVER prints secret values. Confirms .gitignore
# coverage before finishing.
# =============================================================================
set -euo pipefail

WORKTREE="${1:?Usage: worktree-up.sh <worktree-path> <port>}"
PORT="${2:?Usage: worktree-up.sh <worktree-path> <port>}"

if [ ! -d "$WORKTREE" ]; then
  echo "ERROR: worktree path does not exist: $WORKTREE"
  exit 1
fi

API_DIR="$WORKTREE/apps/api"
if [ ! -d "$API_DIR" ]; then
  echo "ERROR: not an OpenChat worktree (no apps/api): $WORKTREE"
  exit 1
fi

# ── .env (idempotent) ─────────────────────────────────────────────────
ENV_FILE="$API_DIR/.env"

cat > "$ENV_FILE" <<EOF
# Generated by tools/worktree-up.sh — DO NOT COMMIT
# Bare-metal API env pointing at the shared dev stack on localhost.

NODE_ENV=development
DEV_AUTH=1
API_PORT=$PORT
WEB_ORIGIN=http://localhost:3000
WEB_PORT=3000

# Postgres — shared dev stack on localhost (postgres:chat from docker-compose.dev.yml)
DATABASE_URL=postgresql://chat:chat@localhost:5432/chat
REDIS_URL=redis://localhost:6379

# OIDC (placeholder — DEV_AUTH=1 bypasses Auth)
OIDC_ISSUER=https://auth.example.com/application/o/chat/
OIDC_CLIENT_ID=dev
OIDC_CLIENT_SECRET=dev-oidc-secret-not-for-prod
OIDC_REDIRECT_URI=http://localhost:3000/api/auth/callback
OIDC_POST_LOGOUT_REDIRECT_URI=http://localhost:3000

# OpenShare
SHARE_BASE_URL=http://localhost:8800
SHARE_API_KEY=dev-share-key

# Jellyfin
JELLYFIN_URL=http://localhost:8096
JELLYFIN_API_KEY=

# LiveKit (dev keys from docker-compose.dev.yml)
LIVEKIT_URL=ws://localhost:7880
LIVEKIT_API_KEY=devkey
LIVEKIT_API_SECRET=secretsecretsecretsecretsecret12
LIVEKIT_API_URL=http://localhost:7880

# Giphy
GIPHY_API_KEY=

# P1-01: bearer access tokens (from docker-compose.dev.yml)
SESSION_SECRET=dev-dev-dev-dev-16
JWT_SECRET=dev-jwt-secret-not-for-prod
EOF

echo "[worktree-up] Wrote $ENV_FILE"

# ── Confirm .env is gitignored ────────────────────────────────────────
pushd "$WORKTREE" > /dev/null
if git check-ignore "$ENV_FILE" > /dev/null 2>&1; then
  echo "[worktree-up] Confirmed .env is gitignored"
else
  echo "ERROR: apps/api/.env is NOT gitignored in this worktree — refusing to proceed"
  popd > /dev/null
  exit 1
fi
popd > /dev/null

# ── Dependencies (idempotent, symlink from shared checkout) ──────────
# node_modules is a SHARED SYMLINK across worktrees. Running npm ci in
# one worktree would corrupt every other agent sharing the same real
# directory. Instead, symlink from the shared checkout (git-common-dir
# parent, or WORKTREE_SHARED_ROOT if set), which is the canonical
# install point.
SHARED_ROOT="${WORKTREE_SHARED_ROOT:-}"
if [ -z "$SHARED_ROOT" ]; then
  SHARED_ROOT="$(cd "$WORKTREE" && git rev-parse --git-common-dir 2>/dev/null | sed 's|/\.git$||')"
fi
if [ -z "$SHARED_ROOT" ]; then
  echo "ERROR: could not determine shared checkout (git rev-parse --git-common-dir failed)"
  exit 1
fi
echo "[worktree-up] Shared checkout: $SHARED_ROOT"

link_node_modules() {
  local rel="$1"
  local target="$SHARED_ROOT/$rel/node_modules"
  local link="$WORKTREE/$rel/node_modules"
  if [ -d "$link" ] && [ ! -L "$link" ]; then
    echo "[worktree-up] $rel/node_modules is a real directory (not a symlink) — refusing to overwrite"
    return 1
  fi
  if [ -L "$link" ]; then
    echo "[worktree-up] $rel/node_modules symlink present — skipping"
    return 0
  fi
  if [ ! -d "$target" ]; then
    echo "[worktree-up] WARNING: $target does not exist — skipping $rel/node_modules symlink"
    echo "[worktree-up]   Run 'npm ci' in the shared checkout first: cd $SHARED_ROOT/$rel && npm ci"
    return 0
  fi
  ln -s "$target" "$link"
  echo "[worktree-up] Symlinked $rel/node_modules → $target"
}

link_node_modules "apps/api"
link_node_modules "apps/mobile"
# Root-level node_modules (husky, etc.) — only if the shared checkout has it
if [ -d "$SHARED_ROOT/node_modules" ]; then
  link_node_modules "."
fi

# ── Prisma generate (idempotent) ──────────────────────────────────────
echo "[worktree-up] Running prisma generate..."
(cd "$API_DIR" && npx prisma generate --schema=prisma/schema.prisma > /dev/null)

echo ""
echo "✅ Worktree ready. Start the API with:"
echo "   PORT=$PORT npm run start:dev"
echo "   (run this in: $API_DIR)"
